services:
  backend:
    environment:
      APP_ENV: "production"
      DEBUG: "false"
      create_tables_on_startup: "false"
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 768M
        reservations:
          cpus: '0.5'
          memory: 512M
    volumes:
      - backend-logs:/app/logs

  celery:
    environment:
      APP_ENV: "production"
      DEBUG: "false"
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 768M
        reservations:
          cpus: '0.5'
          memory: 512M
    volumes:
      - backend-logs:/app/logs

  scheduler:
    environment:
      APP_ENV: "production"
      DEBUG: "false"
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 384M
        reservations:
          cpus: '0.25'
          memory: 256M
    volumes:
      - backend-logs:/app/logs

  frontend:
    environment:
      APP_ENV: "production"
      DEBUG: "false"
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 192M
        reservations:
          cpus: '0.25'
          memory: 128M

  telegram-bot:
    environment:
      APP_ENV: "production"
      DEBUG: "false"
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 192M
        reservations:
          cpus: '0.25'
          memory: 128M

  nginx:
    environment:
      APP_ENV: "production"
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 192M
        reservations:
          cpus: '0.25'
          memory: 128M