ROLE_SUPER_ADMIN = "SUPER_ADMIN"
ROLE_ADMIN = "ADMIN"
ROLE_TRADER = "TRADER"
ROLE_VIEWER = "VIEWER"

USER_STATUS_ACTIVE = "ACTIVE"
USER_STATUS_DISABLED = "DISABLED"

EXCHANGE_STATUS_ACTIVE = "ACTIVE"
EXCHANGE_STATUS_INACTIVE = "INACTIVE"

ASSET_TYPE_CRYPTO = "CRYPTO"
ASSET_TYPE_FOREX = "FOREX"
ASSET_TYPE_STOCK = "STOCK"
ASSET_TYPE_ETF = "ETF"
ASSET_TYPE_COMMODITY = "COMMODITY"
ASSET_TYPE_INDEX = "INDEX"

SIGNAL_BUY = "BUY"
SIGNAL_SELL = "SELL"
SIGNAL_HOLD = "HOLD"

ORDER_TYPE_MARKET = "MARKET"
ORDER_TYPE_LIMIT = "LIMIT"
ORDER_TYPE_STOP = "STOP"

ORDER_SIDE_BUY = "BUY"
ORDER_SIDE_SELL = "SELL"

ORDER_STATUS_NEW = "NEW"
ORDER_STATUS_FILLED = "FILLED"
ORDER_STATUS_CANCELLED = "CANCELLED"
ORDER_STATUS_REJECTED = "REJECTED"

POSITION_STATUS_OPEN = "OPEN"
POSITION_STATUS_CLOSED = "CLOSED"

NEWS_SOURCE_RSS = "RSS"
NEWS_SOURCE_API = "API"
SENTIMENT_PLATFORM_TWITTER = "twitter"
SENTIMENT_PLATFORM_REDDIT = "reddit"
SENTIMENT_PLATFORM_TELEGRAM = "telegram"

INTELLIGENCE_SOURCE_NEWS = "news"
INTELLIGENCE_SOURCE_SOCIAL = "social"
INTELLIGENCE_SOURCE_MACRO = "macro"
